
cargo =	{
  20:"WIG",
  21:"WIG",
  22:"WIG",
  23:"WIG",
  24:"WIG",
  25:"WIG",
  26:"WIG",
  27:"WIG",
  28:"WIG",
  29:"WIG",
  30:"Fishing",
  31:"Towing",
  32:"Towing(l:200m||w:25m)",
  33:"Dredging or underwaterops",
  34:"Diving ops",
  35:"Military ops",
  36:"Sailing",
  37:"Plesure Craft",
  38:"Reserved",
  39:"High Speed Craft",
  40:"HSC",
  41:"HSC",
  42:"HSC",
  43:"HSC",
  44:"HSC",
  45:"HSC",
  46:"HSC",
  47:"HSC",
  48:"HSC",
  49:"HSC",
  50:"Pilot vessel",
  51:"Search and Rescue vessel",
  52:"Tug",
  53:"Port Tender",
  54:"Anti-pollution equipment",
  55:"Law Enforcement",
  56:"Spare - Local Vessel",
  57:"Spare - Local Vessel",
  58:"Medical Transport",
  59:"Noncombatant ship",
  60:"Passenger",
  61:"Passenger, Cat:a",
  62:"Passenger, Cat:b",
  63:"Passenger, Cat:c",
  64:"Passenger, Cat:d",
  65:"Passenger",
  66:"Passenger",
  67:"Passenger",
  68:"Passenger",
  69:"Passenger",
  70:"Cargo",
  71:"cargo",
  72:"cargo",
  73:"cargo",
  74:"cargo",
  75:"cargo",
  76:"cargo",
  77:"cargo",
  78:"cargo",
  79:"cargo",
  80:"Tanker",
  81:"Tanker",
  82:"Tanker",
  83:"Tanker",
  84:"Tanker",
  85:"Tanker",
  86:"Tanker",
  87:"Tanker",
  88:"Tanker",
  89:"Tanker",
  90:"other type",
  91:"other type",
  92:"other type",
  93:"other type",
  94:"other type",
  95:"other type",
  96:"other type",
  97:"other type",
  98:"other type",
  99:"other type"
     
}

status = {
    0:"Under way using engine",
    1:"At anchor",  
    2:"Not under command",
    3:"Restricted manoeuverability",
    4:"Constrained by her draught",
    5:"Moored",
    6:"Aground",
    7:"Engaged in Fishing",
    8:"Under way sailing",
    9:"Reserved for future amendment of Navigational Status for HSC",
    10:"Reserved for future amendment of Navigational Status for WIG",
    11:"Reserved for future use",
    12:"Reserved for future use",
    13:"Reserved for future use",
    14:"AIS-SART is active",
    15:"Not defined (default)"
}
